gcp_project/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

gcp_project/gcp_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    # path('accounting/', include('accounting.urls')),
    # path('contact/', include('contact.urls')),
    # path('expenses/', include('expenses.urls')),
    path('invoices/', include('invoices.urls')),
]

gcp_project/invoices/urls.py
from django.urls import path
from .views import InvoicesListView, InvoiceDetailView, invoice_pdf_view, InvoiceCreateView, InvoiceUpdateView, InvoiceDeleteView, InvoiceRectifyView

app_name = 'invoices'

urlpatterns = [
    path('', InvoicesListView.as_view(), name='invoices'),
    path('<int:pk>/', InvoiceDetailView.as_view(), name='invoice_detail'),
    path('<int:pk>/pdf/', invoice_pdf_view, name='invoice_pdf'),
    path('create/', InvoiceCreateView.as_view(), name='invoice_create'),
    path('<int:pk>/update/', InvoiceUpdateView.as_view(), name='invoice_update'),
    path('<int:pk>/delete/', InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('<int:pk>/rectify/', InvoiceRectifyView.as_view(), name='invoice_rectify'),
]

gcp_project/core/models.py
from django.db import models

gcp_project/core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'core/base.html')

gcp_project/core/templates/core/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ block.title }}Bienvenido a {{ endblock }} - GCP - Gestión Contable Pro</title>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'invoices/css/invoice.css' %}">
    <link href="{% static 'invoices/css/invoice.css' %}" media="print" rel="stylesheet">
    <meta name="description" content="Invoice demo sample">
</head>
<body>
    <nav class="navbar" id="main-navbar">
        <ul>
            <li><a href="/">Inicio</a></li>
            <li><a href="{% url 'invoices:invoices' %}">Facturas</a></li>
        </ul>
    </nav>
    {% block content %}
    <h1>Bienvenido a GCP - Gestión Contable Pro</h1>
    <p>Esta es la página principal de la aplicación.</p>
    {% endblock %}
</body>
</html>